--
SELECT * FROM NOTICES ORDER BY REGDATE DESC;
--
SELECT * FROM NOTICES WHERE CODE = '135';
--
SELECT MAX(TO_NUMBER(CODE))+1 FROM NOTICES;
--r공지사항에서 가장 큰 코드 값
SELECT NVL(MAX(TO_NUMBER(CODE)),0)+1 FROM NOTICES;
SELECT ISNULL(MAX(CAST(CODE AS INT)),0)+1 FROM Notices;

--20개씩 나눈 레코드를 얻어오는 쿼리
--1페이지,2페이지
SELECT * FROM NOTICES ORDER BY REGDATE DESC;
--1페이지
SELECT * FROM (SELECT * FROM NOTIES ORDER BY REGDATE DESC) WHERE ROWNUM BETWEEN 1 AND 20;
--2페이지
SELECT * FROM (SELECT ROWNUM NUM, N.* FROM (SELECT * FROM NOTIES ORDER BY REGDATE DESC) N)
WHERE NUM BETWEEN 6 AND 10;

INSERT INTO NOTICES (CODE,TITLE,WRIETER,CONTENT,REGDATE,HIT) 
VALUES('136','TITLE','HUB','K',SYSDATE,'111');


SELECT (ROW_NUM() OVER (ORDER BY REGDATE DESC)) NUM,NOTICES.*
FROM NOTICES;

SELECT MAX(TO_NUMBER(CODE)) FROM NOTICESFILES;

SELECT MAX(CAST(CODE AS INT))+1 FROM NoticeFiles;

SELECT * FROM NOTICES WHERE REGDATE > (SELECT REGDATE FROM NOTICES WHERE CODE='242')
ORDER BY REGDATE ASC;
SELECT * FROM NOTICES WHERE REGDATE < (SELECT REGDATE FROM NOTICES WHERE CODE='242')
ORDER BY REGDATE DESC;

SELECT * FROM MEMBERS;